---

kaggle_dataset: "grassknoted/asl-alphabet" # Approx 1GB

dataset:
  test: "dataset/asl_alphabet_test"
  train: "dataset/asl_alphabet_train"

featurizers:
  sift:
    pickle: "checkpoints/sift_pickle.z"
    feature_size: 200
  surf:
    pickle: "checkpoints/surf_pickle.z"
    feature_size: 200
  orb:
    pickle: "checkpoints/orb_pickle.z"
    feature_size: 200
  wavelet:
    wavelet: "haar"