---
kaggle_dataset: "grassknoted/asl-alphabet" # Approx 1GB

dataset:
  test: "dataset/asl_alphabet_test"
  train: "dataset/asl_alphabet_train"
  train_examples: 1000 # Training examples per class

featurizers:
  featurizer: "surf"
  sift: # 63.5%
    pickle: "checkpoints/sift_pickle.z"
    feature_size: 400
  surf: # 75%
    pickle: "checkpoints/surf_pickle.z"
    feature_size: 400
  orb: # 28%
    pickle: "checkpoints/orb_pickle.z"
    feature_size: 400
  dwt: # 67%
    wavelet: "haar"
    level: 3
  fft: # 44%
    xdim: 20
    ydim: 20
  rgb:
    xdim: 20
    ydim: 20

classification:
  classifier: "adaboost"
  k-fold: 10 # Number of folds to use in k-fold cross validation
  adaboost:
    tree_max_depth: 3 # Decision tree max depth
    n_estimators: 1000 # Number of decision stumps
    learning_rate: 0.3
    pickle: "checkpoints/adaboost_pickle.z"

app:
  fps: 30
  save_path: saves
