---
kaggle_dataset: "grassknoted/asl-alphabet" # Approx 1GB
always_load: True # Always load pickle files where available
log_level: "quiet" # quiet, debug, warning

dataset:
  test: "dataset/asl_alphabet_test"
  train: "dataset/asl_alphabet_train"
  train_examples: 3000 # Training examples per class

featurizers:
  log_level: "quiet" # quiet, debug, warning
  featurizer: "surf"
  sift: # 63.5%
    pickle: "checkpoints/sift/sift_pickle.z"
    feature_size: 400
  surf: # 76%
    pickle: "checkpoints/surf/surf_pickle.z"
    feature_size: 400
  orb: # 28%
    pickle: "checkpoints/orb/orb_pickle.z"
    feature_size: 400
  dwt: # 67%
    wavelet: "haar"
    level: 3
  fft: # 44%
    xdim: 20
    ydim: 20
  rgb:
    xdim: 20
    ydim: 20

classification:
  log_level: "quiet" # quiet, debug, warning
  classifier: "adaboost"
  k-fold: 10 # Number of folds to use in k-fold cross validation
  adaboost:
    tree_max_depth: 4 # Decision tree max depth
    n_estimators: 1000 # Number of decision stumps
    learning_rate: 0.3
    pickle: "checkpoints/surf/adaboost_pickle.z"

app:
  fps: 30
  save_path: saves
